CLIMADA-project/climada_python

- climada/hazard/__init__.py
- climada/hazard/centroids/base.py
- climada/hazard/centroids/source.py
- climada/hazard/storm_europe.py
- climada/util/files_handler.py
- climada/util/test/test_files.py
- requirements/env_climada.yml
Hi Gabriela,
after a lot of Haareraufen because of git, I finally get around to submitting a PR. Maybe you can just give me commit rights to the original repo? It would avoid the messy commit structure.
By the way: I implemented your advice right away regarding the adm0 centroids attribute. I also switched the centroids logic around a bit, since I didn't want to commit the default WISC centroids pickle. Now it defaults to constructing a barebones Centroids object from the first netcdf file in the list.
best
Jan
> StormEurope class and utility

- climada/hazard/base.py
- climada/hazard/test/test_base.py
The hazard base class has a method .select, which allowed selecting by date, origin, reg_id (and combination of these). To these, I added selecting by track name, which I find very handy
Also applied few PEP related corrections
> add select by name + PEP style corrections

- climada/hazard/tc_tracks.py
- climada/hazard/tc_tracks_synth.py
- climada/hazard/test/test_tc_tracks_synth.py
How about this impementation? Paging @tovogt 
I changed the `tc_tracks_synth.calc_random_walk` to only pass back the data, while still being able to use the instance for its `get_extent` method. Vielen Dank für deine Hilfe :)
> Feature: tc extent

- climada/hazard/centroids/centr.py
- climada/test/test_centr.py
@tovogt I also added a little test for `Centroids().from_base_grid()`. Could you give this a look?
> Centroids: select by extent (aka clipping)

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
I was in need of a method to export my TCForecasts to a database, so I wrote this. I'm only neglecting one line of code in the tests that's really trivial (would return a tuple of DFs instead of one joint DF).
What do you think?
> Feature: TCTracks to GeoDataFrame

- climada/util/plot.py
This is a small util function to make bar plots with multiple bars per element.
> Add multi-bar plot util function

- climada/hazard/test/test_tc_surge_bathtub.py
> tc_surge_bathtub: fix tests for GDAL>=3.1

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
Fix for #169 with regression tests.
> read_ibtracs_netcdf: fix ROCI estimate

- climada/entity/exposures/base.py
- climada/hazard/base.py
- climada/hazard/centroids/centr.py
- climada/hazard/tc_tracks.py
- climada/hazard/trop_cyclone.py
- climada/util/plot.py
This addresses issue #135 and adds the keyword argument `figsize=(9, 13)` to `util.plot.make_plot` and to all the function/methods that call it too.
> util.plot.make_map: Add figsize argument 

- doc/guide/Guide_Git_Development.ipynb
Remove five lines of code that added stock images to the Git guide. They were silly.
> Remove random stock images from Git guide

- climada/hazard/tc_clim_change.py
- climada/hazard/test/test_trop_cyclone.py
- climada/hazard/trop_cyclone.py
This commit reverses the conceptual changes from merge 8084d9a894083d0ad00a0524d0da384f9d4e4374 .
The previous changes lead to negative frequency when applied to historical tracks obtained from IBTrACS.
> Reverse cumulative knutson cc

- climada/hazard/tc_rainfield.py
- climada/hazard/test/test_tc_rainfield.py
Applied time step correction, after #235
> apply time step correction

- climada/entity/exposures/litpop/litpop.py
- climada/test/test_litpop_integr.py
for case last shape in loop over _get_litp…op_single_polygon()  is empty
> litpop: fix NoneType error 

- climada/util/constants.py
> update NONISO_REGIONS with new territories

- climada/util/coordinates.py
> Correct docstring of country_iso2faocode method in util/coordinates

- AUTHORS
- README.md
Added a section ("install with pip") into "getting started" to make the installation easier.
Deleted the former guiding sentences ("download the latest release" and "install dependencies")
> Changed the part "getting started" of readme.md

- doc/tutorial/climada_entity_LitPop.ipynb
- It's very likely that a beginner didn't install at least one of the datasets
> Added a reminder for downloading dataset

- climada/util/plot.py
- climada/util/test/test_plot.py
cit. @blassr "Colorbar was continuous with the new Matplotlib 3.5 version. This is fixed and categorical again with this fix."
> adapt categorical plotting function to new matplotlib version

- climada/hazard/trop_cyclone.py
While playing around with higher resolutions in time and space (i.e., smaller timesteps for TC tracks, and more centroids), I found that the current implementation of `compute_windfield` has quite high memory requirements because there are several temporary numpy arrays that can be avoided with a comparably small code refactor.
The critical arrays are those that store information for each centroid and each track position. This PR reduces the number of such "critical arrays" from 16 to 8. The remaining critical arrays are:
```python
d_centr[:, :]
v_centr_normed[:, :, 0]
v_centr_normed[:, :, 1]
close_centr_msk[:, :]
v_ang_norm[:, :]
v_trans_corr[:, :]
windfields[:, :, 0]
windfields[:, :, 1]
```
For example, when there are 100 track positions, and 5,000,000 centroids, then the memory …
> TropCyclone: lower memory requirements of compute_windfield

- climada/entity/measures/measure_set.py
- Corrected the indentations
This PR fixes these pylint warnings: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/main/2/pylint/folder.-1783209053/fileName.889143554/category.-1505867908/type.-154434559/
> Fixing pylint warnings in measure_set.py

- climada/hazard/tc_tracks.py
- Changed the import path according to the warning message to eliminate the warning
This PR fixes issue #406
> Fixing warning #406 in update_tc_tracks.py

- climada/entity/exposures/base.py
- Changed the argument "url" of the method "plot_basemap" according to the warning message
This PR fixes issue #407
> Fixing the warning #407 in exposure_base.py

- climada/hazard/tc_tracks.py
- Replaced one of the unused variables with "_"
- Deleted the other two unused variables
- Changed a logger message to % format to fix the pylint warning "Logging-fstring-interpolation"
- Ignored the warnings of the type "protected-access"
This PR fixes these pylint issues:
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/809/pylint/fileName.1242641758/category.-1505867908/type.-2051374957/
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/809/pylint/fileName.1242641758/type.1914348128/
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/809/pylint/type.259249251/folder.-914974288/fileName.1242641758/
> Fixing pylint issues in tc_tracks.py

- climada/entity/impact_funcs/base.py
- climada/entity/impact_funcs/impact_func_set.py
-  Fixed a "logging-not-lazy" warning in impact_funcs\base.py and impact_func_set.py
This PR fixes this pylint issues: 
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/813/pylint/type.-846599972/fileName.-456802565/
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/813/pylint/type.-846599972/fileName.1482622882/
> Fixed the "logging-not-lazy" warnings

- climada.conf
- climada/conf/climada.conf
- doc/tutorial/climada_util_api_client.ipynb
- Add a description of how one can use climada in offline mode.
This PR fixes issue #
> API Client Tutorial: add a paragraph about offline mode

- climada/entity/tag.py
- 
- 
This PR fixes issue #
[contrib]: /CONTRIBUTING.md
> update __init__ entity.tag

- climada/hazard/tc_tracks.py
- Following #611, this fixes three problems with the TC track plotting:
1. Tracks that crossed 0 longitude were identified as crossing the antimeridian and had a gap in them when plotted.
2. Tracks that cross the antimeridian had their wind speeds shifted by one frame.
3. Tracks crossing the antimeridian have a line segment removed.
- The solution proposed in this PR is to truncate track segments crossing the antimeridian (instead of removing them). This fixes the first two problems, but it means for the third point that still at least part of the line segments crossing the antimeridian is removed. We discussed in #611 that it is not worth the effort to properly split the affected segments into two segments because it's complicated to implement and probably …
> TCTrack: Fix plotting of segments at antimeridian

- CHANGELOG.md
- requirements/env_climada.yml
- requirements/env_docs.yml
- setup.py
- Remove `pybufrkit` from dependencies 
This PR fixes #661
- ~~[ ] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated~~
> Remove `pybufrkit` from dependencies 

- doc/guide/Guide_Git_Development.ipynb
- A few phrasing updates in the guide for git.
> Small text updates in the git development guide.

- doc/guide/install.rst
- requirements/env_climada.yml
- script/jenkins/install_env.sh
- Allow users to create environments for Python 3.9, 3.10, and 3.11, reverting part of the changes from https://github.com/CLIMADA-project/climada_python/commit/185ef967cdd6a37510421b7d1a69871ed7e4f20d
> Remove python version pin from conda specs

- doc/guide/install.rst
- Fix a dead link
- ~~[ ] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/main/CHANGELOG.md) updated~~
> Fix Miniforge link in install guide

- doc/guide/Guide_Euler.ipynb
- Update Euler Guide for python 3.10 and jupyter.euler.hpc.ethz.ch
> update euler guide

- CHANGELOG.md
- requirements/env_climada.yml
- setup.py
Changes in this PR:
* Set 'nodefaults' because conda-forge is incompatible with Anaconda default channels.
* Set 'pyproj' requirement instead of 'proj'.
This resolves #843 and might help with #836.
See also the update to the Conda package requirements: https://github.com/conda-forge/climada-feedstock/pull/9
> Update environment specs

- .github/workflows/ci.yml
- Update two GitHub CI actions to fix warnings related to outdated version of Node.js used in those actions
> Update GitHub CI action versions

- .github/pull_request_template.md
- Fix broken links in pull request template
> Fix links in pull request template

- doc/climada/climada.entity.rst
- doc/climada/climada.hazard.rst
- fix readthedocs missing modules
- remove tags from readthedocs
This PR fixes #921
> fix read the docs

- doc/misc/citation.rst
- doc/misc/climada_publications.bib
- Add link to flood model paper to citation guide
- Add entry in `climada_publications.bib`
- Update entries for impact function calibration module
> Add flood module paper to citation guide

- climada/hazard/test/__init__.py
- climada/hazard/test/test_tc_tracks.py
- climada/hazard/test/test_tc_tracks_synth.py
- climada/hazard/test/test_trop_cyclone.py
- Make sure that tests are not failing because of a missing IBTrACs-ALL file
> Load IBTrACs file from archive in case

- .github/workflows/ci.yml
> CI/GitHub Actions: set job timeout 20 minutes

- CHANGELOG.md
- doc/guide/Guide_Euler.ipynb
- Add instructions to install climada petals on Euler clusters in guide
Just a small addition in the guide to install petals on Euler. For me, the described instructions worked well.
> Add instructions to install climada petals on Euler

- .github/CODEOWNERS
- .github/workflows/pull-request.yml
- requirements/env_climada.yml
- Add CODEOWNERS file for enabling required reviews on pull requests
- Update pull requests pipeline to make sure the base commit can be found (this sometimes fails)
> Update GitHub infrastructure
