- requirements/env_climada.yml
Add cfgrib from conda-forge to requirements for dealing with grib and bufr files. Also install ECMWFs eccodes.
Grip files are the standart file format for storing weather forecasts. The ECMWF produces eccodes to deal with this file format and suggest to use cfgrib in python (engine for xarray) to open grip files in python. That is why it is important for my work to somehow read grib files. Is cfgrib compatible with our environment? I was able to install it on windows with Anaconda without any problem.
> Add cfgrib to requirements

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
This is a fix for #62. I took the opportunity to add docstrings and unit tests for all the parameter estimation functions.
I would suggest @bguillod as a reviewer because he's already familiar with the problem, but somehow I can't select him (?).
> Don't replace NaNs by -1 when estimating TC track parameters

- climada/hazard/base.py
- climada/hazard/test/test_base.py
I ran into a problem where I wanted to filter hazard events by date and my filtering criterion was silently (!) ignored. This is because the `date` parameter in `Hazard.select` was ignored unless it was a `tuple` object. Passing a list `[date_ini, date_end]` did not work!
This pull request changes this behaviour and adds unit tests to make sure that valid inputs aren't ignored and invalid inputs raise exceptions. Furthermore, it updates the docstring of `Hazard.select`.
All unit tests on Jenkins are successful (see https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/feature%252Fhazard_select_date_invalid/).
> Hazard.select: accept general array-likes as date parameter

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_trop_cyclone.py
- climada/hazard/trop_cyclone.py
*Statement of the problem that this PR is trying to solve:* If the number of centroids is very large (e.g. if it is a global grid of comparably high resolution), the current wind field computation requires prohibitive amounts of memory. This is because, for each track, a dense windfield array is allocated covering all centroids - even those that are far away from the TC track: https://github.com/CLIMADA-project/climada_python/blob/6c27a6120815dde71fe0995ab5f8c963d33398bc/climada/hazard/trop_cyclone.py#L390
*Solution proposed by this PR:* We make sure that only those centroids in the direct vicinity of each TC track (the "reachable" centroids) are regarded in the wind field computation so that computational performance will only depend on the *resolution* of the centroids and not on the …
> Improve performance of wind field computation

- climada/hazard/test/test_tc_tracks_synth.py
I forgot to edit the unit tests so these were not passed after renaming `calc_random_walk` to `calc_perturbed_trajectories`. This pull requests attempts to fix that.
> Fix unit tests for new random walk (calc_perturbed_trajectories)

- climada/hazard/base.py
- climada/hazard/test/test_base.py
This fixes issue #86: If a hazard attribute is a pathos pool, it won't be reset.
> Prevent hazard.base.Hazard.clear from resetting a pool

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
With this update, we can filter CHAZ track simulation data by the ensemble number. CHAZ data files are NetCDF files containing several (usually 40) realizations (ensembles) of the 32y-period 1981-2012. So far, our read-functionality would only support filtering by year. But, naturally, it might come in handy to be able to read only a subset of the (40 or whatever) ensembles.
> TCTracks: Filter CHAZ simulations by ensemble

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
The function `TCTracks.equal_timestep` is currently limited to hourly resolution time steps. I don't think that we have to support arbitrary small time steps, but minute resolution might be useful for some case studies. Since supporting minute resolution is a very easy change and 100% backward compatible, I quickly created a PR for this (with unit test).
While I was at it, I updated the docstrings to NumPy format.
EDIT: Many sub-hour offsets (like 1/360 or 5/60) work well already without this PR. However, this PR now introduces support for arbitrary resolutions.
> TCTracks: interpolate with arbitrary resolution

- climada/hazard/tc_tracks.py
Fix `TCTracks.tracks_in_exp(exposure)` to catch exception when `exposure.geometry` is not defined.
> Fix exception for missing geometry

- climada/util/config.py
With recent config-related changes (#114), CLIMADA uses a config file and, if I want to use a custom config file, it will create clutter in my $HOME because it's not a hidden file (`climada.conf` instead of `.climada.conf`). This PR solves this in a single changed line of code by adding `~/.config/` as a location to look for the `climada.conf` file.
See also #116 for discussions about alternative solutions. This PR is only about adding `~/.config/` to the list of allowed locations for the `climada.conf`. Please don't discuss alternative solutions in this PR.
> Allow ~/.config/ as a location for climada.conf

- climada/hazard/test/test_trop_cyclone.py
- climada/hazard/trop_cyclone.py
- climada/util/coordinates.py
- climada/util/test/test_coordinates.py
As discussed already in a video call, we can improve performance of TC wind field computation by returning to the sinusoidal distance computations (that were default in a legacy version of CLIMADA). The loss in accuracy is very small (compare the values in the tests).
> Improve TC wind performance with sinusoidal projection

- climada/engine/impact.py
- climada/entity/disc_rates/base.py
- climada/entity/exposures/base.py
- climada/entity/exposures/crop_production.py
- climada/entity/impact_funcs/base.py
- climada/entity/measures/base.py
- climada/hazard/base.py
- climada/hazard/tc_surge_bathtub.py
- climada/hazard/tc_tracks.py
- climada/hazard/trop_cyclone.py
- climada/util/test/test_interpolation.py
When computing wind fields from TCTracks and a Centroids object, this PR improves memory efficiency by filtering out centroids early on that are not within reach of any of the TC tracks.
Previously to this PR, filtering was done for coastal centroids, but the reachability was only checked on a track-by-track basis. This would allocate a lot of unnecessary memory when there are many centroids that are never reached by any of the TC tracks.
> Improve TropCyclone memory efficiency for large centroid sets

- climada/entity/exposures/base.py
- climada/entity/exposures/test/test_base.py
As noted in #129, the centroids assignment in `Exposure.assign_centroids` is flawed for raster hazards in three ways:
1. Exposure points that lie outside of the hazard raster in longitudinal, but not in latitudinal directions, are assigned to completely wrong hazard raster points. In other words, exposure points to the (longitudinal) left or right of the hazard raster are affected.
2. The hazard raster is assumed to be nodal instead of cell-centered.
3. The assignment is not by nearest-neighbor, but by next-neighbor-to-the-left (floor instead of round).
This PR is a hot fix to make sure that the current behavior is consistent. A broader discussion of the `assign_centroids` function should remain unaffected by this. We can still change the general behavior later on.
I commited the …
> Fix assign_centroids for raster hazards

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
Following up on #123 about improving the `TCTracks.read_ibtracs_netcdf` function, we found a little issue (#134) in the `TCTracks.equal_timestep` function that affects tracks for which the first time step is not rounded to full hours. More precisely, all tracks are affected for which the first time step is not a multiple of `time_step_h`.
For example, if `time_step_h=1` and the first time step of the track is `06:30:00`, then the output of `equal_timestep` will be a track that starts at `06:00:00` with NaN values. The following time steps (`07:00:00` and so on) will be okay.
Another, more general, example: If `time_step_h=0.75` and the first time step of the track is `02:00:00`, then the output of `equal_timestep` will be a track that starts at `01:30:00` with NaN values. The following …
> TCTracks.equal_timestep: restrict to times within original bounds

- climada/entity/exposures/base.py
- climada/hazard/centroids/centr.py
- climada/util/coordinates.py
- climada/util/plot.py
- climada/util/test/test_coordinates.py
Following the discussion in #139, this PR fixes `climada.util.coordinates.points_to_raster` to correctly handle points that lie in an area crossing the antimeridian.
While I'm at it, I simplified the code of `climada.util.coordinates.read_raster_bounds` which was more complicated than necessary when the given bounds cross the antimeridian.
Similarly, I fixed `Centroids.plot` as well as `Exposures.plot_raster` and `Exposures.plot_hexbin` to correctly handle plot data crossing the antimeridian.
> u_coord.points_to_raster: fix for antimeridian

- climada/engine/impact.py
This fixes #82 (see explanation given there). It's a one-liner.
> Impact._build_exp_event: avoid unnecessary sparse-dense conversion

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
Usually, if an agency reports about a track that crosses the antimeridian, the longitude is always chosen positive within IBTrACS. However, it can happen that the TC crosses the antimeridian according to one agency, but not according to another. When mixing agency data, this can yield inconsistent sign changes in longitude. When using the `interpolate_missing` option, this will lead to wrong interpolated values.
According to my analysis, this only affects a single storm in IBTrACS with the default settings: [2013224N12220](http://ibtracs.unca.edu/index.php?name=v04r00-2013224N12220). However, you never know what might change in the future in IBTrACS. Furthermore, this PR also makes sure that no longitude values are less than -180 (which can happen for some agencies).
> read_ibtracs_netcdf: fix for tracks crossing antimeridian

- climada/entity/exposures/base.py
- climada/entity/exposures/test/test_base.py
Fixes #175 
I changed a test so the hazard.centroids.lat and lon are in float32 which produced an error and then fixed the error as suggested in the issue.
> Bugfix/exposure.assign centroids/coord.dtype

- climada/entity/exposures/base.py
- climada/entity/exposures/test/test_base.py
Before this pull request, old CLIMADA-based code that still accesses data fields of Exposures objects directly would yield this error message:
```
>>> from climada.entity import Exposures
>>> expo = Exposures()
>>> expo['value']
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: 'Exposures' object is not subscriptable
```
This pull request adds a more helpful error message for users coming from CLIMADA 1.x:
```
>>> expo['value']
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "./climada/entity/exposures/base.py", line 228, in _access_item
raise TypeError("Since CLIMADA 2.0, Exposures objects are not subscriptable. Data "
TypeError: Since CLIMADA 2.0, Exposures objects are not subscriptable. Data fields of Exposures objects are …
```
> Exposures: error message on item access

- climada/hazard/centroids/centr.py
This is a small edit to the Centroid class to coerce `Centroid.lat` and `Centroid.lon` to `np.array` objects when they're directly supplied by the user.
Previously a `Centroid` class with user-supplied lat and lon arrays (via `Centroid.set_lat_lon`) preserves the classes of whatever lat/lon data is passed to it. This is fine in most cases, but if it's given a `pandas.Series` (for example, when setting centroids from the lat/lon columns of an `Exposure.gdf`), then the `TropCyclone.set_from_tracks()` method falls  over because it's unable to use `np.nonzero()` on a Series.
Code to reproduce the bug:
```
from climada.hazard import TropCyclone, TCTracks, Centroids
from climada.entity.exposures import LitPop
exp_litpop = LitPop()
exp_litpop.set_country('Puerto Rico', res_arcsec=300)
cent = …
```
> Coerce user-supplied Centroid lat-lon data to np.arrays

- climada/engine/impact.py
- climada/entity/exposures/base.py
- climada/util/coordinates.py
- climada/util/test/test_coordinates.py
The existing method for subsetting an Impact by centroid was very slow when working with Impacts and selections that had large numbers of points.
The culprit was in `Impact._selected_exposures_idx()` which constructed a list of the indices of centroids to select using a list comprehension. I've changed this: it now converts all coordinates to pandas data frames, joins them, and records the indices of common values. It's a lot faster.
There may be an even better way, but this takes large calculations down from ~40 seconds to < 1 sec which is all I need.
Tests all pass 👍
> Improve speed of subsetting an Impact by centroids

- climada/engine/impact.py
- climada/engine/test/test_impact.py
`Impact.select()` takes lists as input for its dates, event_ids and event_names parameters. If you instead pass a numpy array, the method fails at line 1031:
```
if (dates, event_ids, event_names) != (None, None, None):
```
with a ValueError:
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
It's not obvious to the user why this is. So I've added lines at the start of this method to coerce the input to a list. This will allow a bit more flexibility with inputs and when it fails it will be more obvious why.
Questions:
- Do we want to be even more explicit with type checking (e.g. make this a try/except)?
- Could there be any unexpected consequences using `tolist()`here?
> Avoid some errors by coercing some Impact.select() input vars

- climada/util/plot.py
This pull request adds the antimeridian handling to the `util.plot.geo_scatter_from_array` plotting function. The code is copied from `util.geo_bin_from_array`.
As a consequence, the two above functions are identical up to the following lines:
In `geo_bin_from_array` we use `plt.hexbin()`:
```
if 'gridsize' not in kwargs:
kwargs['gridsize'] = min(int(array_im.size / 2), MAX_BINS)
hex_bin = axis.hexbin(coord[:, 1], coord[:, 0], C=array_im,
transform=proj, **kwargs)
```
In `geo_scatter_from_array` we use `plt.scatter()`:
```
scatter = axis.scatter(coord[:, 1], coord[:, 0], c=array_im,
transform=proj, **kwargs)
```
> Update antimeridian handling util.plot.geo_scatter_from_array

- climada/engine/forecast.py
- climada/engine/impact_data.py
- climada/engine/supplychain.py
- climada/entity/exposures/black_marble.py
- climada/entity/exposures/crop_production.py
- climada/entity/exposures/gdp_asset.py
- climada/entity/exposures/litpop.py
- climada/entity/exposures/spam_agrar.py
- climada/entity/exposures/test/test_base.py
- climada/entity/exposures/test/test_gdp_asset.py
- climada/hazard/base.py
- climada/hazard/centroids/test/test_vec_ras.py
- climada/hazard/emulator/geo.py
- climada/hazard/low_flow.py
- climada/hazard/river_flood.py
- climada/hazard/test/test_base.py
- climada/hazard/test/test_flood.py
- climada/hazard/test/test_landslide.py
- climada/hazard/test/test_tc_tracks.py
- climada/hazard/trop_cyclone.py
- climada/test/test_LitPop.py
- climada/test/test_blackmarble.py
- climada/util/constants.py
- climada/util/coordinates.py
- climada/util/test/test_coordinates.py
- requirements/env_climada.yml
- setup.py
Currently, CLIMADA uses the Python package `iso3166` to look up country codes according to the ISO 3166 standard. Unfortunately, that package doesn't cover historical countries that are covered in ISO 3166-3, but only the countries in ISO 3166-1. Furthermore, the package `iso3166` maintains its own database of country codes instead of building upon already existing and well-maintained databases of country codes like Debian's [iso-codes](https://salsa.debian.org/iso-codes-team/iso-codes).
Furtunately, there is an alternative to `iso3166` that is build on Debian's iso-codes: `pycountry`. That package is well-maintained and covers ISO 3166-1 as well as ISO 3166-3 (historic countries), so we don't have to manually deal with those (see #201).
This PR adds the requirement `pycountry` and …
> Use pycountry instead of iso3166 for country code lookup

- climada/engine/impact.py
- climada/engine/test/test_impact.py
`Impact`'s `_build_exp_event` is used in a couple of the plotting methods. It takes an event ID as input and constructs an
exposure object based on the Impact's centroids.
This fixes how it deals with the event ID it's provided: previously it assumed the ID was also the integer position of
that event in the `Impact.event_id` array (i.e. that event IDs are always `[1, 2, 3, ...]`. The fix explicitly finds the event's position before subsetting the impact matrix.
I had a quick look through `Hazard` and `Impact` to see if this bug shows up anywhere else but didn't spot anything.
(No tests seem to test this method)
> Fix Impact's _build_exp_event to work with ids indexing from  > 0

- climada/hazard/tc_tracks_synth.py
This PR fixes issue #199.
However, note that the notebook `climada_engine_Impact.ipynb` should also be edited as follows in cell 4, since
1. `calc_random_walk` has been replaced with `calc_perturbed_trajectories`.
2. This method requires equal timesteps, hence `equal_timestep` must be called before and not after generating synthetic tracks.
```
from climada.hazard import TCTracks, TropCyclone, Centroids
ibtracks_na = TCTracks()
ibtracks_na.read_ibtracs_netcdf(provider='usa', basin='NA', year_range=(2010, 2012), correct_pres=True)
print('num tracks hist:', ibtracks_na.size)
ibtracks_na.equal_timestep(0.5)  # Interpolation to make the track smooth and to allow applying calc_perturbed_trajectories
ibtracks_na.calc_perturbed_trajectories(nb_synth_tracks=1)
print('num tracks hist+syn:', …
```
> Bug fix: impacts tutorial (TC synthetic tracks)

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
The `storm_id` parameter of `read_ibtracs_netcdf` refers to a unique identifier in IBTrACS. Users that specify this parameter are dealing with non-fuzzy information and will most certainly expect to have the correct ID in their hands. Still, the users are only warned in the log output, which might go unnoticed by many users.
With this PR, I propose to raise an exception whenever we find that a user-specified ID is invalid (or non-existing).
What do you think?
As an example why a user might end up specifying a wrong ID: The user might have the ID from a different source and the source might be old or in a strange format. IBTrACS IDs change from time to time, especially for events in the last 2-3 years. Furthermore, if the source contains encoding errors, the specified ID might contain …
> read_ibtracs_netcdf: raise exception for invalid storm ids

- climada/engine/forecast.py
- climada/engine/impact.py
- climada/entity/exposures/base.py
- climada/hazard/centroids/centr.py
- climada/hazard/tc_tracks.py
- climada/hazard/trop_cyclone.py
- climada/util/plot.py
Starting with cartopy 0.19.0, when using grid lines, the axis extent is screwed up if `plt.tight_layout` is called before `set_extent` or before other calls restrict the map extent (see #229).
This PR fixes #229 by moving calls to `tight_layout` from the `make_map` function to a later stage of the plotting.
Issue #229 does not apply to cartopy 0.18.0, but even there (and for future versions), it makes sense to always delay calls to `tight_layout` as much as possible to make sure that all artists or axes are already present and configured when margins and paddings are computed.
> Delay calls to tight_layout as much as possible

- climada/entity/exposures/base.py
- climada/entity/exposures/test/test_base.py
When reading HDF5 exposure files, make sure that the CRS is restored correctly. This fixes #243 because it will also correctly handle very old files (generated with old versions of CLIMADA and/or geopandas).
> Exposures.read_hdf5: restore CRS

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
- climada/hazard/trop_cyclone.py
Following #254, this PR makes sure that track data that is read in using `TCTracks.read_netcdf` has a basin variable instead of the legacy basin string attribute.
> TCTracks.read_netcdf: convert legacy basin attribute on the fly

- climada/hazard/base.py
- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
Originally, this change was part of #245 (now moved to https://github.com/CLIMADA-project/climada_petals/pull/2).
This adds a method `generate_centroids` to the `TCTracks` class that returns a Centroids object covering the region affected by the TC tracks with the specified resolution.
> TCTracks.generate_centroids

- climada/hazard/base.py
- climada/hazard/test/test_base.py
As noted in a discussion about #268, the use of `__dict__` in `Hazard.append` is avoidable. This PR shows how we can avoid it while being 100% backwards compatible.
I did some performance improvements, bug fixes and cleanups along the way. 
To avoid the use of `__dict__` in `TropCyclone.set_from_tracks`, see #272.
> Implement Hazard.append/concat without __dict__

- climada/hazard/base.py
- climada/hazard/tc_tracks.py
- climada/hazard/test/test_base.py
- climada/hazard/test/test_trop_cyclone.py
- climada/hazard/trop_cyclone.py
- doc/tutorial/1_main_climada.ipynb
- doc/tutorial/climada_engine_Impact.ipynb
- doc/tutorial/climada_hazard_TropCyclone.ipynb
As noted in a discussion about #268, the use of `__dict__` in `TropCyclone.set_from_tracks` is avoidable. This PR shows how we can avoid it by introducing a static constructor method `TropCyclone.from_tracks`. While `set_from_tracks` is not removed for backwards compatibility, it is deprecated and replaced by `from_tracks` in all of the tutorials.
This PR is based on #271, so make sure to merge that before looking into this one.
> Implement TropCyclone.from_track without __dict__

- climada/entity/measures/base.py
I assume this is a leftover from the grand if -> impf renaming.
The `Measure.calc_impact` method has a return statement part-way through, with the remainder of the code unreachable, and just a repeat of the earlier code with an intermediate variable renamed from `new_ifs` to `new_impfs`.
I assume it's safe to drop this part!
> Remove unreachable code in Measure class

- climada/entity/exposures/test/test_base.py
- climada/hazard/base.py
- climada/hazard/test/test_base.py
- climada/test/test_hazard.py
- doc/tutorial/climada_engine_Impact.ipynb
- doc/tutorial/climada_hazard_Hazard.ipynb
Part of the big antipattern hunt.
Update `Hazard.set_raster` to `Hazard.from_raster`
Note: we had to add two NEW parameters to the method: `haz_type` and `pool`. Frequently we found code that initiated a Hazard object with haz_type set in the constructor, and then assigned a pool. To do this in one line, we added the extra parameters.
> Update Hazard.set_raster to from_raster in whole core code

- climada/hazard/base.py
This PR fixes issue https://github.com/CLIMADA-project/climada_petals/issues/15.
> hazard.Hazard.from_raster: call the constructor without haz_type

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
This PR makes sure that the data source (provider/reporting agency) of each track and variable generated in `TCTracks.from_ibtracs_netcdf` is stored so that users can better understand where a particular time series came from. The information is stored in the `data_provider` attribute of each track.
Example: `ibtracs_mixed:lat(official_3h),lon(official_3h),wind(official_3h),pres(official_3h),rmw(usa),poci(usa),roci(usa)` means that latitude, longitude, max. wind and min. pressure have been taken from the officially reporting agency while the radius of maximum wind, the environmental pressure and the storm radius have been taken from the `usa` agency.
> from_ibtracs_netcdf: store selected agency for each track variable

- .gitignore
- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
For Hazard and Exposure objects, CLIMADA comes with handy methods to read and write to/from HDF5 files. For `TCTracks` objects, users have to either use pickle (whick has its own issues) or the `write_netcdf` functionality.
The problem with the NetCDF IO is that all tracks are stored in separate files. On many setups, especially with network file systems, the access times for many small files can be extremely bad.
That's why this PR adds IO methods `write_hdf` and `from_hdf` for `TCTracks`, in line with the corresponding functionality for Hazard and Exposure objects. All tracks are stored in a single hdf5 file.
> HDF5 file IO for TCTracks

- climada/engine/impact_data.py
- climada/util/coordinates.py
- climada/util/finance.py
- climada/util/plot.py
- climada/util/test/test_coordinates.py
- climada/util/test/test_finance.py
As discussed in #353, some data has changed in Natural Earth 5.0.0 and will cause several problems. Furthermore, this gets rid of `shapefile.Reader` in favor of `shapereader.Reader`.
> Fixes for Natural Earth 5.0.0 compatibility

- climada/hazard/storm_europe.py
- climada/hazard/test/test_storm_europe.py
The method `StormEurope.from_footprints` resulted in a hazard with infinite frequency when reading a single footprint or a set of footprints from the same year.
This fixes the bug by taking as divisor in the frequency as `np.max([(last_year(haz.date) - first_year(haz.date)), 1])`.
In addition, the docstring for `from_cosmoe_file` and `from_icon_grid` were update to make it clear that the frequency is NOT in 1/years, but 1/(number of runs/ensemble members).
> Fix infinite frequency

- climada/hazard/base.py
- climada/hazard/test/test_base.py
This small fix allows the hazard change centroids to use the meta from the centroids.
> Add change hazard centroids from meta

- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
I just noticed that there is an entry in IBTrACS where longitude values are in a very strange format. For the storm with IBTrACS ID "2016055S15202", the agency NADI reported longitudinal coordinates jumping from 204.30 to -155.73 and back to 204.20 (see http://ibtracs.unca.edu/index.php?name=v04r00-2016055S15202). When restricting to the official 6-hourly reporting intervals, the problem is not present, but many people make use of the unofficial 3-hourly data.
I never expected that something like this would exist, but now that we know that it exists, we have to make sure that CLIMADA normalizes all longitudinal values before applying interpolation. This PR fixes it. And it might also fix problems with other data sets that we don't know about currently.
> TCTracks.equal_timestep: fix for non-normalized longitudes

- climada/util/coordinates.py
- climada/util/test/test_coordinates.py
Hello!
I came across an issue with the unit / order of magnitude of this function. 
Assuming that the max grid cell area should be 2500km^2 (50x50km), I am not sure why we had added *100 in the first place - or am I getting mixed up?
Thanks for having a look!
Best, Carmen
> Fix bug in get_gridcellarea function in util/coordinates

- climada/engine/impact.py
The docstring said the default for `ignore_zero` is `False`, but it was set to `True`. This pull request corrects this and sets it to `False`.
> Change ignore_zero to False as in docstring

- doc/tutorial/climada_entity_LitPop.ipynb
Add warning that computing LitPop exposures may require excessive amounts of RAM. Suggest using the data API instead.
~~*Note*: I have trouble building the docs locally, so I cannot tell yet if everything works out.~~ *Edit: Looks good on my local build now*
Closes #426
> Suggest using data API for LitPop exposures

- doc/guide/Guide_Git_Development.ipynb
This adds a section to the "Git Development" tutorial on how to avoid excessive Git Diffs when changing Jupyter Notebook files. When editing Jupyter Notebooks through a renderer, metadata or entire image files that is/are unrelated to the actual code changes might be modified. Git reports these modifications as changes, which are hard to read as soon as they are committed. The only remedy I see for now is to open the notebooks with a text editor and modify the code then. Of course, the overall layout of the notebooks makes this very inconvenient.
I am unsure if this is the right place to put this information. Suggestions on how to convey this informatin clearly are very welcome!
As a side note, I found [ReviewNB](https://www.reviewnb.com/), a plugin for GitHub that might ease these …
> Add instructions for committing Jupyter Notebook changes

- climada/engine/impact_data.py
- climada/engine/test/test_impact_data.py
- climada/entity/exposures/litpop/litpop.py
- climada/test/test_litpop_integr.py
`pandas.DataFrame.append` is deprecated, which causes a `FutureWarning`.
- Use `pandas.concat` instead of `pandas.DataFrame.append`.
- Update tests to check that `FutureWarning` is not issued anymore.
This resolves the `FutureWarnings` wrt. `append` reported in #423, #402, #401
- ~~[ ] Docs updated~~
> Use pandas.concat in favor of pandas.DataFrame.append

- climada/engine/test/test_impact_data.py
- climada/test/test_litpop_integr.py
- Remove the tests checking for `FutureWarning`s introduced in #443. One of these causes the integration tests to fail.
I figure it's better to remove these checks altogether. Possible future changes in dependency code might lead to more `FutureWarning`s, at which point our tests would start failing.
This PR fixes issue #449.
~~- [ ] Docs updated~~
> Remove tests for FutureWarnings

- climada/util/plot.py
- Suppress UserWarning about losing "important projection information" when converting to a projection string
- To do that the whole get_transformation function is set in a `catch_warnings` block.
This PR addresses issues #413 and #415
> plot.get_transformation: suppress UserWarning about losing information

- climada/engine/forecast.py
- Deleted a line to fix a pylint warning of the type "unused-import"
This PR fixes this pyling warning: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/main/2/pylint/folder.-989414432/fileName.-1603685587/category.-1505867908/type.847887228/
> Fixing pylint warnings in forecast.py

- climada/hazard/base.py
- Tried to ignore the pylint warnings of the time "no-member" that seems to be wrong
This PR fixes these pylint warnings: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/main/2/pylint/folder.-914974288/fileName.-950199065/category.67232232/
(I'll try to finish this all in one commit next time)
> Fixing pylint warnings in base.py

- climada/hazard/centroids/centr.py
- Ignored two pylint warnings of the type "no-member" seem to be wrong
This PR fixes these pylint issues: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/main/2/pylint/fileName.-1333324472/category.67232232/
> Fixing the pylint warnings in centr.py

- climada/entity/exposures/litpop/nightlight.py
- tried to get rid of a pylint warning of the type "unsubscriptable-object" that seems to be wrong
- tried to fix other two pylint warnings of the type "try-except-raise" and "unused-variable" with deleting two lines that won't  be executed
- Ignored a pylint warning of the type "logging-not-lazy" that seems wrong
This PR fixes these pyling warnings: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/main/2/pylint/folder.-1730170293/fileName.-1247442635/category.67232232/source.aabac013-0b32-47b2-a255-7d9ef692e89d/#408
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/main/2/pylint/folder.-1730170293/fileName.-1247442635/category.-1505867908/type.1919915274/source.fdfae969-5840-4cd9-8bcd-223e8495f905/#511 …
> Fixing pylint warnings in nightlight.py

- climada/util/dwd_icon_loader.py
- Used "from" to solve two pylint issues of the types "unused-variable" and "raise-missing-from"
This PR fixes these pylint warnings:
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/main/2/pylint/fileName.269688475/category.-1505867908/type.-1104944142/
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/main/2/pylint/fileName.269688475/category.-1505867908/type.-2051374957/
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/main/2/pylint/type.-846599972/folder.-872054496/
> Fixing pylint issues in dwd_icon_loader.py

- climada/engine/unsequa/calc_base.py
- Ignore a pylint warning of the type "logging-not-lazy" that seems to be wrong
This PR fixes this pylint issues: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/main/2/pylint/type.-846599972/folder.432435459/source.be1ee691-e7a1-4ae1-ac9a-364dbc27bd5b/#74
> Fixing a pylint warning in calc_base.py

- doc/guide/Guide_Euler.ipynb
- The version of Guide_Euler on readthedocs shows some titles in a strange way. Tried to fix that by changing the markdown
This PR doesn't fix any existing issues
> Correcting the markdown of Guide_Euler

- climada/hazard/tc_tracks_synth.py
- Corrected some indentations in tc_tracks_synth.py to fix the pylint warning "bad-indentation"
- Change "," to "%" to fix the pylint warning "raising-format-tuple"
- Ignored the warnings of the type "protected-access"
This PR fixes these pylint warnings: 
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/809/pylint/type.-154434559/source.0d166eef-ed29-4fbc-accb-a79e1f9c6afe/#235
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/809/pylint/fileName.723761345/category.-1505867908/type.267805718/
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/809/pylint/type.259249251/folder.-914974288/fileName.723761345/
> Fixing some pylint warnings in tc_tracks_synth.py

- climada/hazard/centroids/centr.py
- Changed a "ifelse" after "return" to "if"
This PR fixes this pylint warning: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/817/pylint/type.1256717880/
> Fixed the pylint warning "no-else-return" in centr.py

- climada/util/value_representation.py
- Changed the order of the imports
This PR fixes this pylint issue:
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/817/pylint/type.-939583674/folder.-872054496/source.c2938ba8-41fd-47ca-94ce-bfe5393b9c6a/#27
> Fixed the "wrong-import-order" warning in value_representation.py

- climada/engine/calibration_opt.py
- Fixed the pylint warning "unneeded-not"
- Fixed the pylint warnings "wrong-import-order"
This PR fixes these pylint warnings:
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/817/pylint/type.1287284756/source.4d9c0b27-97a4-4f0b-b9f6-03f3d6a70a7e/#114
https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/817/pylint/type.-939583674/folder.-989414432/
> Fixed some pylint warnings in calibration_opt.py

- climada/util/plot.py
- Minor change in util.plot.get_transformation: special case for `climada.constants.DEF_CRS`, EPSG:4326 (WSG 84), use PlateCarree for plotting without issuing a warning
This PR fixes issue #486
~~- [ ] Docs updated~~
~~- [ ] Tests updated~~
> util.plot.get_transformation: special treatment for DEF_CRS

- climada/engine/unsequa/unc_output.py
- shuts the remaining pylint warning of category "High" up
- pure cosmetics
- 
This PR fixes issue #
> silence last severe pylint warning

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
* Add `CONTRIBUTING.md` as landing page for contributors, referenceing the resources in the documentation.
* Extend Pull Request template with reviewer checklist and refer to `CONTRIBUTING.md`.
* Move contribution instructions from `README.md` to `CONTRIBUTING.md` and update them.
- ~~[ ] Tests updated~~
> Add contribution guide and extend pull request template

- climada/util/coordinates.py
- climada/util/test/test_coordinates.py
- In `u_coord.coord_on_land`, use the more stable `latlon_bounds` function to add a buffer around the specified coordinates to avoid problems with global grids where the buffer would increase the bounds beyond 360 degrees in width.
This PR fixes issue #539
[contrib]: /CONTRIBUTING.md
> coord_on_land: fix buffer for global grids

- climada/hazard/base.py
- climada/hazard/tc_tracks.py
- climada/hazard/test/test_tc_tracks.py
- climada/util/coordinates.py
- climada/util/plot.py
- climada/util/test/test_coordinates.py
- Building on #542, introduce a helper function that converts between "extent" and "bounds" convention for the description of a two-dimensional bounding box.
[contrib]: /CONTRIBUTING.md
> Helper function: toggle_extent_bounds

- climada/entity/exposures/base.py
- climada/entity/exposures/test/test_base.py
- climada/entity/measures/test/test_base.py
- climada/util/test/test_coordinates.py
- Fix the recently failing unittests related to a change in `geopandas` where an `AttributeError` would be raised if the `crs` attribute is used on `GeoDataFrame`s without a geometry column.
[contrib]: /CONTRIBUTING.md
> Check crs attribute on GDF if no geo is present

- climada/hazard/test/test_trop_cyclone.py
- climada/hazard/trop_cyclone.py
- Go through the existing TC wind code and double-check units (fixes a bug in Holland et al. 2010 implementation).
- Add a new TC wind model "ER11" that implements Emanuel and Rotunno 2011.
> TropCyclone: Implement ER11 wind model

- climada/util/coordinates.py
- climada/util/test/test_coordinates.py
- replace deprecated `geopandas.GeoDataFrame.append` by `pandas.concat` in `get_admin1_geometries`
This PR is analogous to #443
> util.coordinates.get_admin1_geometries: pd.concat in lieu of gdf.append

- climada/util/coordinates.py
- the util function `get_country_code` raises a `UserWarning` whenever it is called, because `get_country_geometries` returns a GeoDataFrame with EPSG:4326 (WGS84), which is a geographic CRS. Now, accessing a GeoDataFrame with a geogrphic CRS immediately triggers a Warning. This PR simply suppresses the warning.
This PR fixes #415
> uitl.coordinates.get_country_code: ignore UserWarning

- climada/hazard/tc_tracks.py
- Add instructions to the `TCTracks.from_netcdf` docstring on how to load IBTrACS NetCDF files when downloading them manually
- Fix stray unicode symbols in `TCTracks.from_ibtracs_netcdf` docstring
This PR fixes #530
> Add warning not to load IBTrACS with `TCTracks.from_netcdf`

- climada/test/test_plot.py
Increase coverage. Add 3 test to check that the plotting functions of climada/entity/exposure/base.py do not throw
any errors when they are called. Specifically, the functions tested are:
1) plot_scatter
2) plot_raster
3) plot_basemap
I visually checked that the plots were actually plotting something.
> Test plots of Exposure class

- climada/util/plot.py
- climada/util/test/test_plot.py
- Fix a bug in the method `util.plot.geo_im_from_array` .
- Non-default projections were not properly passed over.
> Allow use of non-default projection in plots

- climada/test/test_api_client.py
- climada/util/api_client.py
- Add workaround hints in case someone tries to use get_litpop with multiple countries.
This PR fixes #485
> Improve Error Message of api_client.get_litpop

- requirements/env_docs.yml
- Update `env_doc.yml` to include `sparse`
- 
This PR fixes the documentation. Currently, many of the module docs are missing because the `sparse` module is not part of the `env_doc.yml` specs. Without it, the respective Climada modules cannot be imported and the docstrings are not displayed in the documentation. This fails silently because the autodoc module only issues warnings. On the other hand, we cannot use `sphinx build -W` (which turns warnings into errors), because we have many other warnings during our build.
[linter]: …
> Update doc environment

- .github/pull_request_template.md
- CHANGELOG.md
- doc/guide/Guide_Git_Development.ipynb
- Add a `CHANGELOG.md` file to keep track of changes
- Update PR description template and Git development guide accordingly 
I think keeping a changelog makes much more sense than having the [Upcoming Release](https://github.com/CLIMADA-project/climada_python/wiki/Upcoming-Releases) overview that is detached from the code base.
> Add changelog

- climada/hazard/tc_tracks.py
- Small bugfix: when plotting TCTracks onto an existing axis (passed to `TCTracks.plot`), the variable `proj` is missing. This PR fixes the problem by inferring the projection from the axis object.
This is a one-line fix. No changes to tests, documentation or changelog.
> Small bugfix: infer projection from axis

- climada/hazard/base.py
- Fix the legacy `Hazard.read_hdf5` method to work correctly with derived classes, such as `TropCyclone.` Previously, when calling `haz.read_hdf5(...)` on a `TropCyclone` object, subclass-specific attributes such as `category` or `basin` would be missing from the result.
> Fix Hazard.read_hdf5 for subclasses

- .github/pull_request_template.md
This adds a new entry to the pull request description template, suggesting authors should add a descriptive title (as opposed to the default branch title)
This PR fixes my headache when skimming through PRs.
-  ~~[ ] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#2.--Commenting-&-Documenting) updated~~
-  ~~[ ] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/main/CHANGELOG.md) updated~~ *(feels like this is not necessary here)*
[linter]: …
> Update pull request description template

- CHANGELOG.md
- climada/util/lines_polys_handler.py
- climada/util/test/test_lines_polys_handler.py
- When disaggregating a polygon-containing geodataframe, one needs to specify whether resolution is specified in metres. For gdfs which are already in a projected crs (aka a metre-based one), it is currently strictly necessary to give the resolution (in metres), yet indicate to_metres=False (since else the code tries to re-project the already projected gdf, and fails). This is however a bit confusing to some end-users.
- This hotfix checks in the mentioned case whether the gdf is already projected, and avoids re-projection.
This PR fixes #648
[linter]: …
> Don't re-project projected polygon gdfs in metre-disaggregation

- CHANGELOG.md
- climada/util/config.py
- climada/util/test/test_config.py
- When ever a config value is missing in (beneath) `climada.CONFIG` an error message is provided that is clear about it and suggests a list of files that could be changed to solve the problem.
This PR fixes (to some extent) #665
> Accurate error message for missing configuration

- doc/guide/install.rst
- Instructions for setting up VSCode for
- Using VSCode with Jupyter Notebooks from CLIMADA
- Setting up a workspace
- Setting up the test explorer
> Add setup instructions for VSCode to installatio instructions

- climada/util/test/test_lines_polys_handler.py
- Add test for impact function with different mdd and different id.
> Add one test with different impact function

- doc/guide/install.rst
Modify the section "Verifying Your Installation" in the readthedocs installation instructions.
The command-line command for discovering & executing unittests was erroneous. This is fixed now.
This PR fixes # -
> Update Readthedocs installation / unittest instructions

- climada/test/test_plot.py
This PR fixes issue #693 
The test: climada.test.test_plot.TestPlotter.test_exposures_value_pass was making jenkins run out of memory (> 10GB of RAM usage)
By applying a coarser resolution to the function plot.raster() the RAM usage went down to around 400Mb.
> fix test.test_exposures_value_pass

- climada/util/yearsets.py
- Small bugfix to `yearsets`. An `Impact.at_event` object needs to be a numpy array, or it can't be reindexed in the `Impact.calc_freq_curve` calculation. The `yearsets` class creates these as lists so frequency curve calcuations currently fail. From the documentation they are clearly supposed to be arrays when they are calculated in the `compute_imp_per_year` method. The fix is one line.
> Bugfix: yearsets frequency curve calculations fail

- climada/hazard/base.py
- climada/hazard/test/test_base.py
- The hazard.select Method was setup to only accept lists and silently ignore numpy arrays. This is fixed now. Instead of checking for specific types, it only checks whether the attributes are None.
This PR fixes 
> Allow for numpy arrays in hazard select

- CHANGELOG.md
- climada/engine/impact.py
- climada/engine/test/test_impact.py
- Transform `pyproj.CRS` into WKT string in `Impact.__init__`. WKT is the most precise form of storing CRS information, apart from an actual `CRS` object. This should work fine as the `Impact.crs` attribute can now safely be stored as string, and inserting the WKT into the `Exposures` constructor is supported.
- Fix a subtle bug in an impact test
This PR fixes #706 
> Avoid `Impact` storing a `pyproj.CRS` object

- doc/guide/install.rst
- Following #712, the installation instructions for developers were outdated. This fixes the install guide.
> Docs: Remove env_developer.yml from install guide

- climada/entity/exposures/base.py
- climada/entity/exposures/test/test_nightlight.py
- climada/hazard/base.py
- climada/hazard/centroids/centr.py
- climada/util/coordinates.py
- use the `.geoms` attribute as `mask` argument in case of `MultiPolygon`
This PR fixes https://github.com/CLIMADA-project/climada_petals/issues/79
> upgrade_shapely_2.0_fix

- CHANGELOG.md
- climada.conf
- climada/conf/climada.conf
- climada/util/config.py
- doc/guide/install.rst
- add a novel config value `logging.climada_style` that controls whether or not the logging is configured in the traditional climada style.
This PR fixes #265
> logging best practice

- CHANGELOG.md
- climada/test/test_api_client.py
- climada/util/api_client.py
- doc/tutorial/climada_util_api_client.ipynb
- introduce a purge method in the api_client that removes files from the api client file cache if they are outdated
> cleaning up data api file cache

- CHANGELOG.md
- climada/engine/unsequa/calc_impact.py
- This sets the variable `ImpactCalc.impact(save_mat=False)` to `False` in the `unsequa` module only. Since the change to the `ImpactCalc` class, the default was changed from `False` to `True`, thus it needs to be set explicitly now. This is important as it cost memory and computation time, while the information cannot be processed in the `unsequa` module at the moment.
> Set save_mat=False

- CHANGELOG.md
- climada/engine/impact.py
- climada/engine/impact_calc.py
- climada/engine/impact_data.py
- climada/engine/test/test_impact.py
- climada/engine/test/test_impact_calc.py
- climada/entity/measures/test/test_base.py
- climada/util/yearsets.py
- doc/tutorial/climada_engine_Impact.ipynb
- Remove all uses of `Tag` from `climada/engine/`
> Remove all uses of Tag from climada/engine

- CHANGELOG.md
- climada/test/test_api_client.py
- climada/util/api_client.py
- Small change so that the `api_client.Client.list_dataset_infos` accepts `None` as a property value.
So far only strings and list of strings were accepted. This allows looking for unset properties with the more intuitive `None`. 
Before one had to look for `""`, an empty string.
> api_client: allow searching for None

- climada/engine/unsequa/calc_cost_benefit.py
- climada/engine/unsequa/calc_impact.py
- climada/hazard/base.py
- climada/hazard/tc_tracks.py
- climada/hazard/tc_tracks_synth.py
- climada/hazard/trop_cyclone.py
- When chunksizes for pool.map are calculated, make sure they are at least 1.
This PR fixes #761
> calculated chunksizes greater than zero

- CHANGELOG.md
- climada/hazard/centroids/centr.py
- climada/hazard/centroids/test/test_vec_ras.py
- Correctly pass a list to the function
- Correctly check consistency of input arrays (`allclose` could also throw errors if the arrays had a wrong size, but this was not accounted for)
The original test incorrectly checked for a `ValueError`: The `natural_earth` method would return a string (which was iterable), and a `ValueError` was thrown because a file could not be read from a single character...
This PR fixes the broken pipeline in `develop`
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Stati …
> Fix bug in centroids natural earth feature test

- CHANGELOG.md
- climada/engine/forecast.py
- climada/engine/test/test_forecast.py
- fix hardcoded text elements in the plots of the forecast class
- 
> fix hardcoded text elements in the plots of the forecast class

- CHANGELOG.md
- climada/engine/impact.py
- climada/engine/test/test_impact.py
- Detect if the shape product of the impact matrix is zero instead of the nonzero entries. The latter could also be the case for a correctly-shaped matrix whose values are all zero.
> Make `Impact.impact_at_reg` support all zero impacts

- CHANGELOG.md
- doc/guide/install.rst
- Instructions for installing the `climada-petals` conda package
- Updated instructions for setting up VSCode with pytest
This PR fixes #775.
> Update installation instructions

- climada/util/test/test_lines_polys_handler.py
- Solves upgrade pandas 1.5 -> 2.0 
- Replace `gdf.append` with `pd.concat`.
This PR fixes #700
> Remove pandas append to concat

- CHANGELOG.md
- climada/engine/impact_data.py
- climada/engine/test/test_impact_data.py
`impact_data.emdat_impact_yearlysum` used to concatenate empty data frames, starting with an empty one and then iteratively adding non-empty ones. This triggers a deprecation warning in pandas >= 2.1.
- Instead of starting with an empty DataFrame, all non-empty DatatFrames are gathered in a generator which is then concatenated at once.
> Fix empty data frame concatenation in emdat_impact_yearlysum

- CHANGELOG.md
- climada/util/coordinates.py
- climada/util/test/test_coordinates.py
- use `latlon_bounds` in `climada.util.coordinates.get_country_code`, in order to avoid antimeridian problems
This PR fixes #770
> Antimeridian issue in `get_country_code`

- CHANGELOG.md
- climada/util/coordinates.py
- climada/util/test/test_coordinates.py
- Fix the `dist_approx` util function when used with `method="geosphere"` and `log=True`.
- This only affects very small input values, i.e. computing the distance between points that are very close. I added a unit test for that case. I also added a test case where points are identical because I think that this is a kind of sanity check that should be included.
> Fix dist_approx with "geosphere" method and close points

- AUTHORS.md
- CHANGELOG.md
- climada/util/plot.py
- Add shapes argument to [geo_im_from_array][geo_im_from_array] to allow flexible turning on/off of plotting coastline in [plot_intensity][plot_intensity]
This PR fixes [geo_im_from_array][geo_im_from_array]#
[geo_im_from_array]: https://climada-python.readthedocs.io/en/stable/_modules/climada/util/plot.html
[plot_intensity]: https://climada-python.readthedocs.io/en/stable/climada/climada.hazard.html
> Add shapes argument to geo_im_from_array() in climada.util.plot

- CHANGELOG.md
- climada/util/test/test_yearsets.py
- climada/util/yearsets.py
- skip case distinction in `yearsets.sample_from_poisson`
This PR fixes #819
> fix yearsets.sample_from_poisson

- CHANGELOG.md
- climada/entity/disc_rates/base.py
- climada/entity/disc_rates/test/test_base.py
- add read_csv and write_csv methods in DiscRates class
This PR fixes nothing
> DiscRates csv support

- climada/hazard/test/test_base_xarray.py
- Update the tests because the latest version of xarray (?) changed the error messages slightly
> Fix the exception tests for the latest version of xarray

- CHANGELOG.md
- climada/hazard/base.py
- climada/hazard/test/test_base_xarray.py
* Try interpreting values of the event coordinate as dates or ordinals for default values of `Hazard.date`. If that fails, issue a warning and set default values to zeros.
* Try interpreting values of the event coordinate as dates for default values of `Hazard.event_name`. If that fails, issue a warning and set default values to empty strings.
* Update tests.
The method still tries to read the values as dates but issues a warning if that does not work. The fallback is zeros in case of `Hazard.date` and empty strings for `Hazard.event_name`.
This extends #795, which actually introduced tighter restrictions for the 'event' coordinate. This causes several issues in my new flood module, see https://github.com/CLIMADA-project/climada_petals/pull/64.
This fixes …
> Allow reading Hazard events that are not dates from xarray

- CHANGELOG.md
- climada/engine/unsequa/test/test_unsequa.py
- climada/test/test_api_client.py
- climada/test/test_plot.py
- climada/util/api_client.py
- doc/tutorial/climada_util_api_client.ipynb
- Adds a convenience method to the Client, `get_dataset_file`, which combines get_dataset_info and download_dataset, thus reducing boilerplate code.
> api-client get_dataset_file

- CHANGELOG.md
- climada/test/test_engine.py
- climada/util/test/test_finance.py
- fix reference numbers in test cases
This PR fixes #835
> adapt to changed worldbank data

- AUTHORS.md
- CHANGELOG.md
- climada/engine/impact.py
- climada/engine/test/test_impact.py
- add a reset_frequency option in impact.select(), analogue to [hazard.select()](https://github.com/CLIMADA-project/climada_python/blob/e41222210bfb99e92829c0a86f1db2f31355abf5/climada/hazard/base.py#L1300)
- 
This PR fixes #830 
> add impact.select reset_frequency option

- CHANGELOG.md
- climada/engine/impact.py
- Only call `np.unique` once in `Impact.impact_at_reg`.
- 
This seems to have been an oversight during the review of #642.
> Avoid redundant calls to `np.unique` in `Impact.impact_at_reg`

- climada/hazard/base.py
- requirements/env_climada.yml
- xarray 2024.2 introduced an AttributeError in `year_month_day_accessor` of `Hazard.from_xarray_raster` where: the `array` argument is not reallly a date-time array. This PR fixes the problem by simply adding the Exception type to the list of caught Exceptions.
- However, the update to xarray 2024.2 also seems to slow down the procedure significantly. On a personal computer the test `test_base_xarray.TestReadDefaultNetCDF.test_event_no_time` took between 6 and 8 seconds where it finished in 1 to 2 seconds with version 2024.1
This PR fixes #852
[linter]: …
> update to xarray 2024.2

- climada/util/coordinates.py
- climada/util/test/test_coordinates.py
> Bugfix lon_bounds returning range > 360 degrees

- AUTHORS.md
- CHANGELOG.md
- climada/engine/impact_calc.py
- climada/engine/test/test_impact_calc.py
- Add a test in `ImpactCalc.impact(exposures, impfset, hazard)` to handle AttributeError arising when an impact function id contained in the exposures has no matching impact function in the impact function set.
- Change previous `AttributeError: 'list' has no attribute 'calc_mdr'` to a more explanatory error message
This PR fixes #669 (reopened)
> Improve impact calc error messages when there is a mismatch of impf ids between exposures and impfset

- doc/guide/Guide_Euler.ipynb
- update the Euler user guide to the newest version (the only version that runs with current develop branch) 
> euler user guide update

- climada/hazard/base.py
- climada/hazard/centroids/centr.py
- climada/hazard/test/test_base.py
This pull request is a fix for issue #879. 
An empty centroids is created in the `Hazard.concat()` function with the crs from the haz object from the haz_list.
> Create an empty centroids in Hazard.concat() with CRS from the first haz_list.

- CHANGELOG.md
- CONTRIBUTING.md
- doc/guide/install.rst
- Allow a downgrading of the Python bugfix version by using a wildcard.
This increases compatibility, as Conda will first install the latest (requested) Python version and then run into compatibility issues when updating the environment with the Climada dependencies. The wildcard allows Conda to downgrade to a compatible bugfix version of Python, e.g. 3.11.9 → 3.11.6.
- Update links in `CONTRIBUTING.md`
This PR fixes #903 
> Allow downgrading of Python and update links in contribution guide

- CHANGELOG.md
- climada/engine/impact.py
- climada/engine/test/test_impact.py
- Call `str` on values if decoding strings from `event_name` fails, issue a warning in this case.
- Throw error during writing if `event_name` is not strings.
- Fix an issue where only the first value of `event_name` was checked.
This PR fixes  #807
> Explicitly convert `event_name` to strings in `Impact.from_hdf5`

- CHANGELOG.md
- climada/util/plot.py
- climada/util/test/test_plot.py
- doc/tutorial/climada_hazard_Hazard.ipynb
- In the plot function `geo_im_from_array`, NaN values in the data will be plotted in gray. Before, NaN value were not plotted (i.e. transparent), making them indistinguishable from plot regions for which there is no data (no centroids).
- In the plot function `plot_from_gdf`, the colorbar with will be shown on a logarithmic scale if a) the gdf is about return periods or impacts, b) there are no zeros in the data, c) the span of the data's values are at least two orders of magnitude
[linter]: https://climada-python.readthedocs.io/en/latest/guide/Guide_continuous_integration_GitHub_actions.h …
> plot NaNs in gray color and use log color bar

- CHANGELOG.md
- climada/util/interpolation.py
- climada/util/test/test_interpolation.py
- new util module `interpolate.py` with which data can be linearly interpolated (and extrapolated) using the function `interpolate_ev` or interpolated with a stepfunction using the function `stepfunction_ev`. Options include thresholds and log scales. Also, a util function `group_frequency` is added to group frequencies for constant intensitity or impact values. These util functions will later be used in the functions `Impact.local_exceedance_impact`, `Hazard.local_exceedance_intensity`, `Hazard.local_return_period`, see PR #918. 
This PR is the first part of PR #918 (splitted for length reasons) that will fix #904, #915 and partially also #209.
[testing]: …
> New interpolation util functionality

- doc/guide/Guide_Py_Performance.ipynb
- doc/tutorial/1_main_climada.ipynb
- doc/tutorial/climada_entity_DiscRates.ipynb
- doc/tutorial/climada_entity_Exposures.ipynb
- doc/tutorial/climada_entity_ImpactFuncSet.ipynb
- doc/tutorial/climada_entity_MeasureSet.ipynb
- doc/tutorial/climada_hazard_Hazard.ipynb
- Warns and discourages users to use pickle for any long term saving in tutorial/documentation.
- Adds a short section in Best Practice explaining the cons of using pickle.
Climada offers the possibility to use pickle to save most objects. Yet, this format is dependent on the python environment used when saving any object and thus offer very limited portability. 
This is tied to SCRUM task 149 and User Story 148 (Improve saving conventions for Climada objects)
[linter]: https://climada-python.readthedocs.io/en/latest/guide/Guide_continuous_integration_GitHub_actions.html#static-code-analysi …
> Warn about and discourage the use of pickle to save objects

- doc/guide/install.rst
- script/jenkins/install_env.sh
- setup.py
- Adjust doc and config file so that they point to python 3.11 as the default version
> default installation with python 3.11

- CHANGELOG.md
- climada/engine/test/test_impact_calc.py
- climada/hazard/base.py
- climada/hazard/test/test_base.py
- Fixes a bug in the impact calculation for cases with a single exposure point and a zero MDR value.
This PR fixes #933
> Bug fix in Hazard.get_mdr and impact calculation in case of a single exposure point and MDR values of 0

- CHANGELOG.md
- climada/hazard/isimip_data.py
- climada/hazard/storm_europe.py
- climada/hazard/tc_tracks.py
- doc/guide/Guide_Py_Performance.ipynb
Replace all occurrence of `data = xr.open_dataset(filename)` with `with xr.open_dataset(filename) as data:` to ensure filestream closing. See #920 on why this can cause problems.
Using `data = xr.open_dataset(filename)` assumes a data.close() afterwards to correctly close the filestream. This is not done in all function. The pythonic approach is to use a context manager `with ... as ... :` which handle the closing.
See also: https://github.com/pydata/xarray/issues/2887
This PR fixes #920 
[linter]: https://climada-python.readthedocs.io/en/latest/guide/Guide_continuous_integration_GitHub_act …
> Use context manager for xarray dataset file opening

- CHANGELOG.md
- climada/hazard/centroids/centr.py
- climada/hazard/centroids/test/test_centr.py
Refer to https://github.com/CLIMADA-project/climada_python/issues/988 for detailed information on the profiling results.
Modify `hazard.append()` function in `climada/hazard/centroids/centr.py` so that concatenation of centroids is made only once, when all centroids has already been appended, instead of concatenating every time a centroid is appended (extremely time consuming)
- Create centroid attribute `batch_gdf` in hazard.append()
- Append centroids to `batch_gdf`
- Define concatenation function: `finalize_append()`
- Call `finalize_append()` to concatenate at the end of the appending process
- Clear `batch_gdf` attribute
This PR fixes #988 
Optimize the function `TropCyclone.from_tracks` from 53 minutes to 4.03 minutes.
[contrib]: …
> optimize concatenation of centroids

- CHANGELOG.md
- climada/util/plot.py
Context:
In PR #929, we introduced that in `util.plot.geo_im_from_array`, locations with NaN are plotted in gray and locations without a centroid (more precisely, outside the convex hull of the given centroids) are plotted in white. This created problems with `matplotlib.pyplot.pcolormesh`, which, for some proj inputs, created NaNs inside the given data that covered the values that should be plotted.
- The background color of the plot is now gray (NaN color), using axis.set_facecolor, and values without centroid (ie outside convex hull) are plotted in white with cmap.set_under. Like this, locations with only NaNs are plotted in gray, and locations with NaNs and a valid value are plotted with the valid value. Before, NaNs were plotted in gray using …
> Hotfix: plot NaNs in geo_im_from_array

- .github/workflows/ci.yml
- CHANGELOG.md
- climada/util/finance.py
- climada/util/test/test_finance.py
- requirements/env_climada.yml
- setup.py
Use JSON/pandas solution for downloading World Bank indicator data.
* Add function `download_world_bank_indicator`.
* Add unit test.
* Remove `pandas-datareader` from requirements.
This PR fixes #987 
> Remove pandas-datareader

- climada/test/test_litpop_integr.py
- climada/util/finance.py
- climada/util/test/test_finance.py
- Raise a `ValueError` in `download_world_bank_indicator` instead of a `RuntimeError`
as this is caught in `gdp` to then use `nat_earth_adm0` instead
This PR fixes #1049
> Raise ValueError in download_world_bank_indicator

- climada/hazard/test/test_tc_tracks.py
- `gopandas.datasets` is deprecated and has been removed from geopandas >= 1.0
- in climada, the module is used exactly once, in test_tc_tacks, to create an exposures object from 110m admin 0 cultural vectors
- The nearly very same data can be downloaded via cartopy.io.shapereader
- In particular, for Cuba, which is the only relevant country in this test, the data is exactly equal.
This PR renders upgrading geopandas to 1.0 possible.
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continuous_Integration_and_Testing.html#3.C.--Static-Code-Analysi …
> remove geopandas.datasets

- CHANGELOG.md
- climada/engine/impact.py
- climada/hazard/plot.py
- climada/util/plot.py
- Add an optional parameter to `geo_im_from_array` such that the user can input a (relative) distance above which plot locations that are further away than this distance from any centroids are masked (ie, no values plotted). This option is then available in all function that call `geo_im_from_array`, i.e., `_event_plot`, `hazard.plot_intensity`, `hazard.plot_fraction`, `plot_from_gdf`, `hazard.plot_rp_intensity`, `impact.plot_rp_imp`
- removed bug about the NaN legend in `geo_im_from_array`
[linter]: https://climada-python.readthedocs.io/en/stable/guide/Guide_Continu …
> Add option in raster plot to crop around centroids

- climada/engine/cost_benefit.py
- climada/engine/test/test_cost_benefit.py
- climada/entity/measures/base.py
- If a Measure included a new exposure object with no hazard centroids assigned, this led to an error message that was not clear how to resolve, see #1056. Now the method checks if there are assigned centroids and assigns them if not.
This PR fixes #1056
> Hotfix: assign centroids in cost benefit impact calculation if in new exposure no centroids were assigned

- doc/user-guide/climada_entity_MeasureSet.ipynb
- Remove explicit write example from measure tuto.
> Remove explicit write example from measure tuto.

- CHANGELOG.md
- climada/engine/impact.py
- climada/hazard/plot.py
- climada/util/plot.py
- Substantially speeding up plots by directly adding all borders with one call, rather than loop through each geometry object, when adding countries and coastlines in the `u_plot.add_shapes` function. I've tested the new function in multiple tutorials and my own data (both with standard and projected coordinates) and the plots look equivalent. 
- Set the default value of the recently implemented mask_distance in hazard plots from 0.01 to 0.03.
This PR fixes #1071 
Substantially speeds up hazard.plot_intensity (and other functions that use `u_plot.add_shapes`). Before the update, adding the country borders took up to 75% of the overall time, which is reduced to <1%, significantly speeding up the overall function. 
The change of the default mask_distance is …
> speed-up the function to add country borders and coastlines

- doc/misc/citation.rst
-
-
This PR updates the DOI link in the "Impact Calculations" section to:
https://doi.org/10.5194/gmd-12-3085-2019
> Fix DOI link in Impact Calculations (citation.rst)
